source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RecordButton_Example' do
  pod "RecordButton", :path => "../"
end

target 'RecordButton_Tests' do
  pod "RecordButton", :path => "../"
end
